# Generated by Django 3.1.1 on 2024-04-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_num',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
