# Generated by Django 3.1.1 on 2024-04-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20240403_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('starting_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_name', models.CharField(max_length=100)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('refund_situation', models.CharField(max_length=100)),
                ('registration_date', models.DateField()),
                ('number_of_classes', models.IntegerField()),
                ('already_registered_for_courses', models.CharField(max_length=100)),
                ('course_hours_completed', models.IntegerField()),
                ('paid_class_hours', models.IntegerField()),
                ('remaining_class_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course', models.CharField(max_length=255)),
                ('lesson_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_name', models.CharField(max_length=100)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_costs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=100)),
                ('payee', models.CharField(max_length=255)),
                ('remark', models.TextField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
    ]
