# Generated by Django 3.1.1 on 2024-04-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20240403_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveReportTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('status', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FeedbackStaff',
            new_name='FeedbackTeacher',
        ),
        migrations.RenameModel(
            old_name='NotificationStaff',
            new_name='NotificationTeacher',
        ),
        migrations.RenameField(
            model_name='feedbackteacher',
            old_name='staff',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='notificationteacher',
            old_name='staff',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='staff',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Teacher'), (3, 'Student')], default=1, max_length=1),
        ),
        migrations.RenameModel(
            old_name='Staff',
            new_name='Teacher',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.AddField(
            model_name='leavereportteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher'),
        ),
    ]
