# Generated by Django 3.1.1 on 2024-04-08 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20240408_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherQuery',
        ),
        migrations.RenameField(
            model_name='studentquery',
            old_name='course_hours_completed',
            new_name='completed_hours',
        ),
        migrations.RenameField(
            model_name='studentquery',
            old_name='already_registered_for_courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='studentquery',
            old_name='number_of_classes',
            new_name='num_of_classes',
        ),
        migrations.RenameField(
            model_name='studentquery',
            old_name='refund_situation',
            new_name='refunded',
        ),
        migrations.RenameField(
            model_name='studentquery',
            old_name='registration_date',
            new_name='reg_date',
        ),
        migrations.RenameField(
            model_name='studentquery',
            old_name='remaining_class_hours',
            new_name='remaining_hours',
        ),
        migrations.AddField(
            model_name='studentquery',
            name='contact_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='registered_courses',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentquery',
            name='session',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
