# Generated by Django 3.1.1 on 2024-04-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20240408_1228'),
        ('main_app', '0009_paymentrecord_status'),
    ]

    operations = [
    ]
