# Generated by Django 3.1.1 on 2024-04-08 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20240408_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentquery',
            old_name='instructor',
            new_name='teacher',
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='gender',
            field=models.ForeignKey(choices=[('M', 'Male'), ('F', 'Female')], on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
