# Generated by Django 3.1.1 on 2024-04-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_auto_20240408_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.subject'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher'),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='class_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='starting_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.student'),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
