# Generated by Django 3.1.1 on 2024-04-08 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20240408_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquery',
            name='class_ending_time',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='class_starting_time',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='completed_hours',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='contact_num',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='date',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='num_of_classes',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='paid_class_hours',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='refunded',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='reg_date',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='registered_courses',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='remaining_hours',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='session',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='state',
        ),
        migrations.RemoveField(
            model_name='studentquery',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentquery',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
