# Generated by Django 3.1.1 on 2024-04-08 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20240408_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('num_of_classes', models.IntegerField(null=True)),
                ('registered_courses', models.CharField(max_length=100, null=True)),
                ('completed_hours', models.IntegerField(null=True)),
                ('paid_class_hours', models.IntegerField(null=True)),
                ('remaining_hours', models.IntegerField(null=True)),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('learning_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.learningrecord')),
                ('payment_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.paymentrecord')),
                ('student_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
    ]
