# Generated by Django 3.1.1 on 2024-04-08 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_teacherquery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherQuery',
        ),
    ]
