# Generated by Django 3.1.1 on 2024-04-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_delete_teacherquery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='lesson_unit_price',
        ),
    ]
