# Generated by Django 3.1.1 on 2024-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_remove_classschedule_lesson_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='lesson_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
