# Generated by Django 3.1.1 on 2024-04-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20240409_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquery',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='date',
            field=models.DateField(),
        ),
    ]
