# Generated by Django 3.1.1 on 2024-04-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20240409_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='lesson_unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
