# Generated by Django 3.1.1 on 2024-04-09 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_auto_20240409_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentquery',
            name='student',
        ),
        migrations.AddField(
            model_name='studentquery',
            name='student_records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='learning_records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.learningrecord'),
        ),
    ]
