# Generated by Django 3.1.1 on 2024-04-10 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20240410_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_staff',
            new_name='is_teacher',
        ),
    ]
