# Generated by Django 3.1.1 on 2024-04-10 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20240410_1317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentQuery',
        ),
    ]
