# Generated by Django 3.1.1 on 2024-04-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_studentquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='teacher status'),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='completed_hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='num_of_classes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='paid_class_hours',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='refund',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='registered_courses',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentquery',
            name='remaining_hours',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
