# Generated by Django 3.1.1 on 2024-04-12 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_auto_20240412_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_classes', models.IntegerField(null=True)),
                ('completed_hours', models.IntegerField(null=True)),
                ('remaining_hours', models.IntegerField(default=0, null=True)),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('learning_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.learningrecord')),
                ('teacher_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher')),
            ],
        ),
    ]
