# Generated by Django 3.1.1 on 2024-04-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_teacherquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cell_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuser',
            name='home_number',
            field=models.TextField(default=''),
        ),
    ]
