# Generated by Django 3.1.1 on 2024-04-25 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0034_auto_20240424_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='remark',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
