# Generated by Django 3.1.1 on 2024-04-25 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0037_auto_20240425_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
        migrations.AddField(
            model_name='campus',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher'),
        ),
    ]
