# Generated by Django 3.1.1 on 2024-04-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_auto_20240425_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='student',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='teacher',
        ),
        migrations.AddField(
            model_name='campus',
            name='students',
            field=models.ManyToManyField(related_name='campuses', to='main_app.Student'),
        ),
        migrations.AddField(
            model_name='campus',
            name='teachers',
            field=models.ManyToManyField(related_name='campuses', to='main_app.Teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_institutions', to='main_app.institution'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='teacher_institutions', to='main_app.institution'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='main_app.institution'),
        ),
    ]
