# Generated by Django 3.1.1 on 2024-04-26 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_auto_20240426_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='courses',
        ),
    ]
