# Generated by Django 3.1.1 on 2024-04-26 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_remove_campus_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='main_app.student'),
        ),
        migrations.RemoveField(
            model_name='campus',
            name='teacher',
        ),
        migrations.AddField(
            model_name='campus',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='campuses', to='main_app.Teacher'),
        ),
    ]
