# Generated by Django 3.1.1 on 2024-04-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_auto_20240426_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='student',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='main_app.student'),
        ),
        migrations.RemoveField(
            model_name='campus',
            name='teacher',
        ),
        migrations.AddField(
            model_name='campus',
            name='teacher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='main_app.teacher'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
