# Generated by Django 3.1.1 on 2024-04-26 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0047_auto_20240426_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='student',
        ),
        migrations.RemoveField(
            model_name='campus',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.campus'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='teacher status'),
        ),
    ]
