# Generated by Django 3.1.1 on 2024-04-29 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0049_auto_20240429_1052'),
    ]

    operations = [
        
        
    ]
