# Generated by Django 3.1.1 on 2024-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_remove_customuser_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='campus',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
