# Generated by Django 3.1.1 on 2024-04-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_auto_20240428_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='campus',
        ),
    ]
