# Generated by Django 3.1.1 on 2024-04-30 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0050_auto_20240429_1636'),
        ('main_app', '0052_auto_20240429_1344'),
    ]

    operations = [
    ]
