# Generated by Django 3.1.1 on 2024-05-06 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0054_auto_20240430_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='contact_num',
        ),
    ]
