# Generated by Django 3.1.1 on 2024-05-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0055_remove_customuser_contact_num'),
        ('main_app', '0053_remove_customuser_campus'),
    ]

    operations = [
    ]
