# Generated by Django 3.1.1 on 2024-05-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0056_merge_20240506_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
