# Generated by Django 3.1.1 on 2024-05-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0059_auto_20240508_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cell_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='home_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
