# Generated by Django 3.1.1 on 2024-05-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0060_auto_20240508_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='student',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
