# Generated by Django 3.1.1 on 2024-05-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0062_auto_20240508_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
