# Generated by Django 3.1.1 on 2024-05-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0063_student_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningrecord',
            old_name='starting_time',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='remark',
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='lesson_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
