# Generated by Django 3.1.1 on 2024-05-09 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0064_auto_20240509_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningrecord',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
