# Generated by Django 3.1.1 on 2024-05-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0065_learningrecord_admin'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='learningrecord',
        #     name='lesson_hours',
        #     field=models.TextField(default=''),
        # ),
    ]
