# Generated by Django 3.1.1 on 2024-05-09 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0067_auto_20240509_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='learning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.learningrecord'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='teacher status'),
        ),
    ]
