# Generated by Django 3.1.1 on 2024-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0068_auto_20240509_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.TextField(default=''),
        ),
    ]
