# Generated by Django 3.1.1 on 2024-05-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0069_paymentrecord_lesson_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='lesson_hours',
        ),
    ]
