# Generated by Django 3.1.1 on 2024-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0070_remove_paymentrecord_lesson_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.TextField(default=''),
        ),
    ]
