# Generated by Django 3.1.1 on 2024-05-10 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0073_refundrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refundrecord',
            name='amount_refunded',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='amount_to_be_refunded',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='hours_remaining',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='hours_spent_learning',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='lesson_unit_price',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='total_duration_of_lesson',
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='admin',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='payment_records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.paymentrecord'),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='refund',
            field=models.CharField(default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='student_records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='lesson_hours',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='refundrecord',
            name='reason_for_refund',
            field=models.TextField(default=''),
        ),
    ]
