# Generated by Django 3.1.1 on 2024-05-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0074_auto_20240510_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refundrecord',
            old_name='payment_records',
            new_name='payment_record',
        ),
        migrations.RenameField(
            model_name='refundrecord',
            old_name='student_records',
            new_name='student',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='reason_for_refund',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='refund',
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='amount_refunded',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='refundrecord',
            name='refund_reason',
            field=models.TextField(null=True),
        ),
    ]
