# Generated by Django 3.1.1 on 2024-05-10 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0076_auto_20240510_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='learning',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.learningrecord'),
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount_refunded', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('refund_reason', models.TextField(null=True)),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('learning_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.learningrecord')),
                ('payment_records', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.paymentrecord')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
    ]
