# Generated by Django 3.1.1 on 2024-05-10 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0077_auto_20240510_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='lesson_hours',
        ),
    ]
