# Generated by Django 3.1.1 on 2024-05-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0079_remove_paymentrecord_learning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='class_name',
        ),
    ]
