# Generated by Django 3.1.1 on 2024-05-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0081_paymentrecord_learning_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'verbose_name_plural': 'Payment Records'},
        ),
    ]
