# Generated by Django 3.1.1 on 2024-05-10 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0082_auto_20240510_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={},
        ),
    ]
