# Generated by Django 3.1.1 on 2024-05-10 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0085_auto_20240510_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendancereport',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='feedbackteacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='feedbackteacher',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='lesson_hours',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='leavereportteacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leavereportteacher',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notificationstudent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='notificationteacher',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='notificationteacher',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='classes',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='lesson_hours',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='classes',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.classes'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.DeleteModel(
            name='LessonHours',
        ),
    ]
