# Generated by Django 3.1.1 on 2024-05-11 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0086_auto_20240510_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='lesson_hours',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='class_time',
        ),
        migrations.RemoveField(
            model_name='learningrecord',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='refundrecord',
            name='admin',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='lesson_hours',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='lesson_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.classschedule'),
        ),
    ]
