# Generated by Django 3.1.1 on 2024-05-11 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0087_auto_20240511_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='classschedule',
            name='classes',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.grades'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.grades'),
        ),
    ]
