# Generated by Django 3.1.1 on 2024-05-11 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0088_auto_20240511_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Grades',
        ),
    ]
