# Generated by Django 3.1.1 on 2024-05-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0089_auto_20240511_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
