# Generated by Django 3.1.1 on 2024-05-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0090_auto_20240511_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='lesson_hours',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
