# Generated by Django 3.1.1 on 2024-05-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0092_auto_20240511_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningrecord',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='grade',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
