# Generated by Django 3.1.1 on 2024-05-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0093_auto_20240511_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningrecord',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='lesson_hours',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='learningrecord',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
