# Generated by Django 3.1.1 on 2024-05-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0099_auto_20240511_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
