# Generated by Django 3.1.1 on 2024-05-14 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0102_auto_20240513_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='next_payment_date',
            field=models.DateField(null=True),
        ),
    ]
