# Generated by Django 3.1.1 on 2024-05-16 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0105_paymentquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningrecord',
            name='class_schedule',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_record', to='main_app.classschedule'),
        ),
    ]
