# Generated by Django 3.1.1 on 2024-05-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0106_learningrecord_class_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningrecord',
            name='class_schedule',
        ),
    ]
