# Generated by Django 3.1.1 on 2024-05-17 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0107_remove_learningrecord_class_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningrecord',
            old_name='schedule',
            new_name='schedule_record',
        ),
    ]
