# Generated by Django 3.1.1 on 2024-05-17 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0108_auto_20240517_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.IntegerField(),
        ),
    ]
