# Generated by Django 3.1.1 on 2024-05-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0110_teacher_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='date_of_birth',
        ),
    ]
