# Generated by Django 3.1.1 on 2024-05-19 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0111_remove_teacher_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationteacher',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notificationteacher',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationteacher',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
