# Generated by Django 3.1.1 on 2024-05-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0112_auto_20240519_1022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='status',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='test',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, default='Currently Learning', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.classes'),
        ),
    ]
