# Generated by Django 3.1.1 on 2024-05-17 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0112_auto_20240517_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
