# Generated by Django 3.1.1 on 2024-05-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0113_auto_20240519_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='classes',
            new_name='schedule',
        ),
    ]
