# Generated by Django 3.1.1 on 2024-05-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0113_auto_20240517_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(related_name='courses', to='main_app.Teacher'),
        ),
    ]
