# Generated by Django 3.1.1 on 2024-05-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0114_course_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
    ]
