# Generated by Django 3.1.1 on 2024-05-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0114_auto_20240519_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='schedule',
            new_name='classes',
        ),
    ]
