# Generated by Django 3.1.1 on 2024-05-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0115_auto_20240519_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
