# Generated by Django 3.1.1 on 2024-05-18 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0116_auto_20240517_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='test',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.course'),
        ),
        migrations.AddField(
            model_name='studentresult',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.session'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, default='Currently Learning', max_length=30),
        ),
    ]
