# Generated by Django 3.1.1 on 2024-05-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0117_auto_20240518_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='session',
        ),
        migrations.AddField(
            model_name='studentresult',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.classes'),
        ),
    ]
