# Generated by Django 3.1.1 on 2024-05-20 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0117_attendance_students'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='attendance',
        #     name='students',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        # ),
    ]
