# Generated by Django 3.1.1 on 2024-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0120_auto_20240520_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackteacher',
            name='created_at',
            field=models.DateField(),
        ),
    ]
