# Generated by Django 3.1.1 on 2024-05-20 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0122_auto_20240520_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackteacher',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
