# Generated by Django 3.1.1 on 2024-05-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0123_auto_20240520_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackteacher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
