# Generated by Django 3.1.1 on 2024-05-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0124_auto_20240520_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_semester',
            field=models.IntegerField(default=1),
        ),
    ]
