# Generated by Django 3.1.1 on 2024-05-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0126_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campus',
            name='principal',
            field=models.CharField(default='principal', max_length=100),
        ),
        migrations.AddField(
            model_name='campus',
            name='principal_contact_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
