# Generated by Django 3.1.1 on 2024-05-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0128_studentsummary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSummary',
        ),
    ]
