# Generated by Django 3.1.1 on 2024-05-21 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0129_delete_studentsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='feedbackteacher',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='FeedbackStudent',
        ),
        migrations.DeleteModel(
            name='FeedbackTeacher',
        ),
    ]
