# Generated by Django 3.1.1 on 2024-05-21 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0130_auto_20240521_1637'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='summaryteacher',
        #     name='student',
        #     field=models.ForeignKey(default='------', on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        # ),
    ]
