# Generated by Django 3.1.1 on 2024-05-21 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0131_summaryteacher_student'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='summaryteacher',
        #     name='student',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        # ),
    ]
