# Generated by Django 3.1.1 on 2024-05-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0132_auto_20240521_1711'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='summaryteacher',
        #     name='student',
        # ),
    ]
