# Generated by Django 3.1.1 on 2024-05-21 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0133_remove_summaryteacher_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryteacher',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.student'),
        ),
    ]
