# Generated by Django 3.1.1 on 2024-05-22 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0134_summaryteacher_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryteacher',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summaryteacher',
            name='reply',
            field=models.TextField(blank=True),
        ),
    ]
