# Generated by Django 3.1.1 on 2024-05-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0135_auto_20240522_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summaryteacher',
            name='reply',
            field=models.TextField(),
        ),
    ]
