# Generated by Django 3.1.1 on 2024-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0136_auto_20240522_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryteacher',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
