# Generated by Django 3.1.1 on 2024-05-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0137_summaryteacher_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summaryteacher',
            name='is_hidden',
        ),
    ]
