# Generated by Django 3.1.1 on 2024-05-22 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0138_remove_summaryteacher_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationteacher',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AddField(
            model_name='notificationteacher',
            name='payment_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.paymentrecord'),
        ),
        migrations.AddField(
            model_name='notificationteacher',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.student'),
        ),
    ]
