# Generated by Django 3.1.1 on 2024-05-24 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0139_auto_20240522_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='learning_record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_record', to='main_app.learningrecord'),
        ),
    ]
