# Generated by Django 3.1.1 on 2024-05-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0141_auto_20240524_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='lesson_unit_price',
        ),
    ]
