# Generated by Django 3.1.1 on 2024-05-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0148_auto_20240527_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherquery',
            name='num_of_classes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
