# Generated by Django 3.1.1 on 2024-05-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0149_auto_20240527_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningrecord',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
