# Generated by Django 3.1.1 on 2024-05-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0150_learningrecord_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecord',
            name='day',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
