# Generated by Django 3.1.1 on 2024-05-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0151_auto_20240527_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
