# Generated by Django 3.1.1 on 2024-05-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0152_course_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
