# Generated by Django 3.1.1 on 2024-05-28 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0153_classschedule_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='hourly_rate',
        ),
    ]
