# Generated by Django 3.1.1 on 2024-05-28 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0155_classschedule_hourly_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classschedule',
            old_name='day_of_week',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='course',
            name='hourly_rate',
        ),
    ]
