# Generated by Django 3.1.1 on 2024-05-28 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0156_auto_20240528_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='hourly_rate',
        ),
    ]
