# Generated by Django 3.1.1 on 2024-05-28 09:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0157_remove_classschedule_hourly_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='hours_missed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='book_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='learning_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.learningrecord'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='lesson_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='next_payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payee',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Refund', 'Refund')], default='Paid', max_length=20),
        ),
    ]
