# Generated by Django 3.1.1 on 2024-05-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0159_remove_attendancereport_hours_missed'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='hours_missed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
