# Generated by Django 3.1.1 on 2024-05-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0160_attendancereport_hours_missed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='hours_missed',
        ),
    ]
