# Generated by Django 3.1.1 on 2024-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0161_remove_attendancereport_hours_missed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='payment_method',
            field=models.CharField(choices=[('WeChat', 'WeChat'), ('AliPay', 'AliPay'), ('Bank Card', 'Bank Card'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Refund', 'Refund'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='', max_length=20),
        ),
    ]
