# Generated by Django 3.1.1 on 2024-05-31 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0163_auto_20240531_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
