# Generated by Django 3.1.1 on 2024-05-31 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0164_auto_20240531_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.IntegerField(default=0),
        ),
    ]
