# Generated by Django 3.1.1 on 2024-05-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0165_auto_20240531_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentrecord',
            name='lesson_hours',
        ),
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='main_app.Course'),
        ),
    ]
