# Generated by Django 3.1.1 on 2024-05-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0166_auto_20240531_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.IntegerField(default=0),
        ),
    ]
