# Generated by Django 3.1.1 on 2024-06-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0171_auto_20240601_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('男', 'Male'), ('女', 'Female')], max_length=1),
        ),
    ]
