# Generated by Django 3.1.1 on 2024-06-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0172_auto_20240601_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecord',
            name='lesson_hours',
            field=models.TimeField(null=True),
        ),
    ]
