# Generated by Django 3.1.1 on 2024-06-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0174_auto_20240602_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='lesson_hours',
            field=models.IntegerField(null=True),
        ),
    ]
