# Generated by Django 3.1.1 on 2024-06-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0175_auto_20240603_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='lesson_hours',
            field=models.TimeField(null=True),
        ),
    ]
