# Generated by Django 3.1.1 on 2024-06-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0176_auto_20240603_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='lesson_hours',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='learningrecord',
            name='lesson_hours',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.IntegerField(default=0),
        ),
    ]
