# Generated by Django 3.1.1 on 2024-06-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0180_auto_20240603_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classschedule',
            name='lesson_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
