# Generated by Django 3.1.1 on 2024-06-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0181_auto_20240603_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='main_app.Course'),
        ),
    ]
