# Generated by Django 3.1.1 on 2024-06-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0182_auto_20240603_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecord',
            name='lesson_hours',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
