# Generated by Django 3.1.1 on 2024-06-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0183_auto_20240603_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='lesson_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
