# Generated by Django 3.1.1 on 2024-06-05 01:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0187_auto_20240604_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='TuitionReminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('payment_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.paymentrecord')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.teacher')),
            ],
        ),
    ]
