# Generated by Django 3.1.1 on 2024-06-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0188_tuitionreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningrecord',
            name='day',
            field=models.CharField(default='星期一', max_length=20, null=True),
        ),
    ]
