# Generated by Django 3.1.1 on 2024-06-05 03:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0189_auto_20240605_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuitionreminder',
            name='due_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
