# Generated by Django 3.1.1 on 2024-06-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0190_tuitionreminder_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuitionreminder',
            old_name='is_sent',
            new_name='is_read',
        ),
    ]
