# Generated by Django 3.1.1 on 2024-06-07 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0192_remove_tuitionreminder_payment_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.campus'),
        ),
    ]
