# Generated by Django 3.1.1 on 2024-06-07 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0193_attendance_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='campus',
        ),
    ]
