# Generated by Django 3.1.1 on 2024-06-14 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0194_remove_attendance_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main_app.campus'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='main_app.campus'),
        ),
    ]
