# Generated by Django 3.1.1 on 2024-06-14 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0195_auto_20240614_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='main_app.campus'),
        ),
    ]
